# base image
image: "ruby:2.5.3"

# Services
services:
  - postgres:latest

# default variables
variables:
  RAILS_ENV: test
  POSTGRES_DB: tamashii
  NODE_VERSION: 8.0.0
  YARN_VERSION: 0.24.6
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"

# build stages
stages:
  - test
  - staging
  - production

# cache gems in between builds
cache:
  paths:
    - vendor/ruby
    - node_modules

# this is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - if [[ ! -f /usr/local/bin/node ]]; then curl -SLO https://nodejs.org/dist/v$NODE_VERSION/node-v${NODE_VERSION}-linux-x64.tar.xz && tar -xJf node-v${NODE_VERSION}-linux-x64.tar.xz -C /usr/local --strip-components=1; fi
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - apt-get update && apt-get install apt-transport-https
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt-get update && apt-get install yarn
  - gem install bundler -v 1.15.1 --no-ri --no-rdoc    # bundler is not installed with the image
  - ruby -v
  - node -v
  - yarn -v
  - bundle install -j $(nproc) --path vendor  # install dependencies into ./vendor/ruby
  - yarn install

# jobs
rspec:
  stage: test
  script:
    - bundle exec rake db:schema:load
    - bundle exec rspec -p

rubocop:
  stage: test
  services: []
  before_script:
    - gem install rubocop -v 0.49.1
  script:
    - rubocop

eslint:
  stage: test
  image: "node:8.1"
  services: []
  before_script:
    - yarn
  script:
    - yarn run eslint


scsslint:
  stage: test
  services: []
  before_script:
    - gem install scss_lint
  script:
    - scss-lint app/assets/stylesheets/

deploy_to_production:
  stage: production
  only:
    - master
  before_script:
    - gem install bundler -v 1.13.7 --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  environment: production
  script:
    - cap production deploy
