export const RECEIVE_CHECK_RECORDS = 'RECEIVE_CHECK_RECORDS';
export const CHECK_RECORD_SET = 'CHECK_RECORD_SET';
export const NOTIFY_NEW_RECORD = 'NOTIFY_NEW_RECORD';

export default RECEIVE_CHECK_RECORDS;
